### ISSUE TITLE
Ty tępy eryku czemu iso ma 800mb

### ISSUE THREAD

**Issue by indexerrowaty** [xiboon/microarch#2]
https://user-images.githubusercontent.com/39349444/161448438-81a27eb0-860f-4066-8337-2fd01360a7c3.mp4

CIUPAK CIUPAK TY CIUPAK

![photo_2022-03-21 21 47 41](https://user-images.githubusercontent.com/39349444/161448444-b33d0f0f-27cf-416c-8848-afb89f471a60.jpeg)
RIK RIK RIK

![photo_2022-03-20 16 57 05](https://user-images.githubusercontent.com/39349444/161448455-0baa1fe3-d288-419d-9e56-3877fcc74e9a.jpeg)
ADEK NIEEEEE!!!!!!!

**Comment by hkubus** [comment]
bo iso potrzebuje w huj

**Comment by indexerrowaty** [comment]
aha noob głupek
ave maryja
![R2_GBC_-_Unused_Anim_1](https://user-images.githubusercontent.com/39349444/161448508-19c00323-af85-4714-90e2-9b85bb61fb37.gif)

https://user-images.githubusercontent.com/39349444/161448513-51452786-3eef-4489-b888-349b36977f2a.mp4
